### PR TITLE
Added attachments

### PR DESCRIPTION
**Pull request by robertf224**
Added two lines to Message class to support attachments and an Attachment class to represent attachment objects.  Attachments to an email are stored in an array (message.attachments).  Attachment objects have name and size (kilobytes) properties, and their associated files can be saved to disk using the save() function, which optionally takes a path to save the file to.  I updated the README to show capabilities, though you very well might want to represent the information differently.

### CODE REVIEW

**Comment by lesthack** [comment]
iv'e a problem with this search:
g.inbox().mail(unread=True, attachment=True)

**Comment by ekianjo** [comment]
So what's the status on this functionality ? what works and what does not work ?

**Comment by robertf224** [comment]
All I added was access to the attachments (if there are any) of fetched emails wrapped as objects of a convenience Attachment class.  You can see how to access them in the Readme of my fork of the project.  I'll look into allowing a search for emails with attachments when I have time next week!

**Comment by odino** [comment]
Any plan to merge this? :)

**Comment by charlierguo** [comment]
Yep! I've just gotten back from traveling for the past few months, so I
haven't had a lot of time for development, but I'll be taking a look at all
the issues and pull requests.

**Pull request merged**
